[package]
name = "subaru_web_ql"
version = "0.1.0"
authors = ["jvo203 <chris.zapart@nao.ac.jp>"]

[dependencies]
iron = "*"
staticfile = "*"
router = "*"
mount = "*"
urlencoded = "*"
lazy_static = "*"
xml-rs = "*"
curl = "*"
scan_fmt = "*"
